# Site settings
title: Maximo Mena
email: maximo.mena@gmail.com
description: Hi! I'm Maximo Mena and I blog about things that are interesting to me such as web development, dancing, fitness, and traveling.
baseurl: ""
url: "http://www.iammaximo.com"
twitter_username: mmenavas 
github_username: mmenavas

# Build settings
markdown: kramdown
